[2013-12-06 02:40:38] log.ERROR: 500 - Class 'validators_connexion' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_connexion' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:41:46] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:42:18] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:42:55] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:44:27] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:44:47] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:45:52] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:49:45] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:50:40] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:53:06] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('isTakenUsername', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->isTakenUsername(NULL)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('isTakenUsername', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->isTakenUsername(NULL)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('isTakenUsername', Array)
#7 [internal function]: User->isTakenUsername(NULL)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): Illuminate\Database\Eloquent\Model::__callStatic('isTakenUsername', Array)
#10 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#11 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#18 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#19 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#20 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#21 [internal function]: UserController->postRegister()
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#32 {main} [] []
[2013-12-06 02:53:41] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('isTakenUsername', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->isTakenUsername(NULL)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('isTakenUsername', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->isTakenUsername(NULL)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('isTakenUsername', Array)
#7 [internal function]: User->isTakenUsername(NULL)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): Illuminate\Database\Eloquent\Model::__callStatic('isTakenUsername', Array)
#10 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#11 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#18 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#19 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#20 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#21 [internal function]: UserController->postRegister()
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#32 {main} [] []
[2013-12-06 02:54:05] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:54:18] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:55:54] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select count(*) as aggregate from `utilisateur` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select count(*) as aggregate from `utilisateur` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:58:29] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `utilisateur` (`email`, `username`, `password`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7EcyW7LR3Gxs9uijmn3j8uNKCsF17owj9MMln/MjVTQ/eiz4DNk1m',
  3 => '2013-12-06 02:58:29',
  4 => '2013-12-06 02:58:29',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `utilisateur` (`email`, `username`, `password`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7EcyW7LR3Gxs9uijmn3j8uNKCsF17owj9MMln/MjVTQ/eiz4DNk1m',
  3 => '2013-12-06 02:58:29',
  4 => '2013-12-06 02:58:29',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UserController->postRegister()
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
[2013-12-06 02:58:57] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$xrEU5R.uzYd5hSarNFNvtu8kyjMXwDzNSd5vHyMNtsZPuS49r9RWi',
  3 => '2013-12-06 02:58:57',
  4 => '2013-12-06 02:58:57',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: UserController->postRegister()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$xrEU5R.uzYd5hSarNFNvtu8kyjMXwDzNSd5vHyMNtsZPuS49r9RWi',
  3 => '2013-12-06 02:58:57',
  4 => '2013-12-06 02:58:57',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 02:59:06] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7YW/vFJDLiStX6pbfXodCOfcjpEWxOna1IFYgzYkN0IDExzyHEwTS',
  3 => '2013-12-06 02:59:06',
  4 => '2013-12-06 02:59:06',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7YW/vFJDLiStX6pbfXodCOfcjpEWxOna1IFYgzYkN0IDExzyHEwTS',
  3 => '2013-12-06 02:59:06',
  4 => '2013-12-06 02:59:06',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UserController->postRegister()
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
[2013-12-06 02:59:34] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::connexion() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::connexion()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('connexion', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->connexion(1)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('connexion', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->connexion(1)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('connexion', Array)
#7 [internal function]: User->connexion(1)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\controllers\UserController.php(42): Illuminate\Database\Eloquent\Model::__callStatic('connexion', Array)
#10 D:\xampp\htdocs\azertea\app\controllers\UserController.php(42): User::connexion(1)
#11 [internal function]: UserController->postRegister()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2013-12-06 03:03:20] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `utilisateur` where `username` = ? limit 1) (Bindings: array (
  0 => 'username',
)) @ /user/connect
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(63): Illuminate\Database\Eloquent\Builder->first()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#11 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#15 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#16 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Auth::attempt(Array)
#17 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('connexion', Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateConnexi...', Array)
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateConnexion('username', 'username', Array, Object(Illuminate\Validation\Validator))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'connexion')
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#24 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#25 D:\xampp\htdocs\azertea\app\validators\validators_user.php(18): BaseValidator->test(Array)
#26 D:\xampp\htdocs\azertea\app\controllers\UserController.php(21): validators_user->login()
#27 [internal function]: UserController->postLogin()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#33 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#34 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#37 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#38 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `utilisateur` where `username` = ? limit 1) (Bindings: array (
  0 => 'username',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(63): Illuminate\Database\Eloquent\Builder->first()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#14 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#15 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Auth::attempt(Array)
#16 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('connexion', Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateConnexi...', Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateConnexion('username', 'username', Array, Object(Illuminate\Validation\Validator))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'connexion')
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#23 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#24 D:\xampp\htdocs\azertea\app\validators\validators_user.php(18): BaseValidator->test(Array)
#25 D:\xampp\htdocs\azertea\app\controllers\UserController.php(21): validators_user->login()
#26 [internal function]: UserController->postLogin()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#33 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#34 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#37 {main} [] []
[2013-12-06 03:04:19] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::connexion() @ /user/connect
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::connexion()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('connexion', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->connexion(1)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('connexion', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->connexion(1)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('connexion', Array)
#7 [internal function]: User->connexion(1)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\controllers\UserController.php(24): Illuminate\Database\Eloquent\Model::__callStatic('connexion', Array)
#10 D:\xampp\htdocs\azertea\app\controllers\UserController.php(24): User::connexion(1)
#11 [internal function]: UserController->postLogin()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2013-12-06 03:08:56] log.ERROR: 500 - Class ProductController does not exist @ /annonce/add
exception 'ReflectionException' with message 'Class ProductController does not exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php:308
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('ProductControll...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('ProductControll...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('ProductControll...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('ProductControll...')
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2013-12-06 03:09:33] log.ERROR: 500 - syntax error, unexpected '$v' (T_VARIABLE), expecting function (T_FUNCTION) @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$v' (T_VARIABLE), expecting function (T_FUNCTION)' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:20
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:10:43] log.ERROR: 404 - Controller method not found. @ /annonce/add
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('postProductAdd', Array)
#2 [internal function]: AnnonceController->postProductAdd()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postProductAdd', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postProductAdd', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 03:11:53] log.ERROR: 404 - Controller method not found. @ /annonce/add
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('postProductAdd', Array)
#2 [internal function]: AnnonceController->postProductAdd()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postProductAdd', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postProductAdd', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 03:12:16] log.ERROR: 500 - Class 'validators_add_annonce' not found @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_add_annonce' not found' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:18
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:12:54] log.ERROR: 500 - Call to undefined method validators_add_annonce::login() @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method validators_add_annonce::login()' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:14:04] log.ERROR: 500 - Class 'Annonce' not found @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Annonce' not found' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:21
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:15:08] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list' (SQL: insert into `annonce` (`nomProduit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:08',
  7 => '2013-12-06 03:15:08',
)) @ /annonce/add
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `an...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `an...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: AnnonceController->postAnnonce()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list' (SQL: insert into `annonce` (`nomProduit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:08',
  7 => '2013-12-06 03:15:08',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `an...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: AnnonceController->postAnnonce()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 03:15:43] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `annonce` (`nom_produit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:43',
  7 => '2013-12-06 03:15:43',
)) @ /annonce/add
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `an...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `an...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: AnnonceController->postAnnonce()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `annonce` (`nom_produit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:43',
  7 => '2013-12-06 03:15:43',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `an...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: AnnonceController->postAnnonce()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 03:26:21] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:13
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:27:25] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:15
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:27:31] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:15
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:27:41] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:15
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:28:13] log.ERROR: 500 - syntax error, unexpected ';', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:28:23] log.ERROR: 500 - syntax error, unexpected ';', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:28:59] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:31
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:29:15] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:50
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:29:28] log.ERROR: 500 - syntax error, unexpected '=', expecting ')' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=', expecting ')'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:50
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:32:18] log.ERROR: 500 - Method [validateInt] does not exist. @ /tree
exception 'BadMethodCallException' with message 'Method [validateInt] does not exist.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:1908
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateInt', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateInt('categories', '3', Array, Object(Illuminate\Validation\Validator))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('categories', 'int')
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#4 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#5 D:\xampp\htdocs\azertea\app\validators\validators_search.php(16): BaseValidator->test(Array)
#6 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(26): validators_search->tree()
#7 [internal function]: SearchController->postTree()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postTree', Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postTree', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-12-06 03:32:18] log.ERROR: 500 - Method [validateInt] does not exist. @ /tree
exception 'BadMethodCallException' with message 'Method [validateInt] does not exist.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:1908
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateInt', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateInt('categories', '3', Array, Object(Illuminate\Validation\Validator))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('categories', 'int')
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#4 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#5 D:\xampp\htdocs\azertea\app\validators\validators_search.php(16): BaseValidator->test(Array)
#6 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(26): validators_search->tree()
#7 [internal function]: SearchController->postTree()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postTree', Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postTree', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-12-06 03:34:47] log.ERROR: 500 - Method [validateInt] does not exist. @ /tree
exception 'BadMethodCallException' with message 'Method [validateInt] does not exist.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:1908
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateInt', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateInt('categories', '3', Array, Object(Illuminate\Validation\Validator))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('categories', 'int')
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#4 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#5 D:\xampp\htdocs\azertea\app\validators\validators_search.php(16): BaseValidator->test(Array)
#6 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(26): validators_search->tree()
#7 [internal function]: SearchController->postTree()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postTree', Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postTree', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-12-06 04:01:52] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entreprise' in 'field list' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `entreprise`) values (?, ?, ?)) (Bindings: array (
  0 => 40483304800022,
  1 => 'Amazon',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entreprise' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `en...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#6 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#7 [internal function]: {closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entreprise' in 'field list' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `entreprise`) values (?, ?, ?)) (Bindings: array (
  0 => 40483304800022,
  1 => 'Amazon',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:02:47] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'approuve' in 'field list' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `approuve`) values (?, ?, ?)) (Bindings: array (
  0 => 40483304800022,
  1 => 'Amazon',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'approuve' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `en...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#6 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#7 [internal function]: {closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'approuve' in 'field list' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `approuve`) values (?, ?, ?)) (Bindings: array (
  0 => 40483304800022,
  1 => 'Amazon',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:03:04] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 49867876889022,
  1 => 'CDiscount',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY'' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#6 D:\xampp\htdocs\azertea\app\models\Populate.php(34): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#8 [internal function]: {closure}()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 49867876889022,
  1 => 'CDiscount',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(34): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:03:26] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 49867876889022,
  1 => 'CDiscount',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY'' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#6 D:\xampp\htdocs\azertea\app\models\Populate.php(34): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#8 [internal function]: {closure}()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4294967295' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 49867876889022,
  1 => 'CDiscount',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(34): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:04:42] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.utilisateurs' doesn't exist (SQL: insert into `utilisateurs` (`pseudo`, `email`, `mdp`, `est_valide`, `id_particulier`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'AzerTea',
  1 => 'azer@tea.com',
  2 => 'df6b9fb15cfdbb7527be5a8a6e39f39e572c8ddb943fbc79a943438e9d3d85ebfc2ccf9e0eccd9346026c0b6876e0e01556fe56f135582c05fbdbb505d46755a',
  3 => true,
  4 => 1,
)) @ /
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.utilisateurs' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\app\models\Populate.php(47): Illuminate\Database\Query\Builder->insert(Array)
#6 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#7 [internal function]: {closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.utilisateurs' doesn't exist (SQL: insert into `utilisateurs` (`pseudo`, `email`, `mdp`, `est_valide`, `id_particulier`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'AzerTea',
  1 => 'azer@tea.com',
  2 => 'df6b9fb15cfdbb7527be5a8a6e39f39e572c8ddb943fbc79a943438e9d3d85ebfc2ccf9e0eccd9346026c0b6876e0e01556fe56f135582c05fbdbb505d46755a',
  3 => true,
  4 => 1,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(47): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:04:57] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY'' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#6 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#8 [internal function]: {closure}()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:05:22] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY'' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#6 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#8 [internal function]: {closure}()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:05:34] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'poids' in 'field list' (SQL: insert into `MC_cat` (`id_MC`, `id_categorie`, `poids`) values (?, ?, ?)) (Bindings: array (
  0 => 1,
  1 => 1,
  2 => 4,
)) @ /
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'poids' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `MC...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `MC...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `MC...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `MC...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `MC...', Array)
#5 D:\xampp\htdocs\azertea\app\models\Populate.php(231): Illuminate\Database\Query\Builder->insert(Array)
#6 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#7 [internal function]: {closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'poids' in 'field list' (SQL: insert into `MC_cat` (`id_MC`, `id_categorie`, `poids`) values (?, ?, ?)) (Bindings: array (
  0 => 1,
  1 => 1,
  2 => 4,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `MC...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `MC...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `MC...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `MC...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(231): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:08:59] log.ERROR: 500 - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
)) @ /
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY'' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#6 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#7 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#8 [internal function]: {closure}()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4048332' for key 'PRIMARY' (SQL: insert into `entreprise` (`n_Siret`, `nom`, `aprouve`) values (?, ?, ?)) (Bindings: array (
  0 => 4048332,
  1 => 'Amazon',
  2 => true,
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `en...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `en...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `en...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `en...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(30): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:10:49] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.particulier' doesn't exist (SQL: insert into `particulier` (`nom`, `prenom`, `telephone`) values (?, ?, ?)) (Bindings: array (
  0 => 'BONHOURE',
  1 => 'Pierre',
  2 => '0657654599',
)) @ /
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.particulier' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `pa...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pa...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pa...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pa...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `pa...', Array)
#5 D:\xampp\htdocs\azertea\app\models\Populate.php(12): Illuminate\Database\Query\Builder->insert(Array)
#6 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#7 [internal function]: {closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.particulier' doesn't exist (SQL: insert into `particulier` (`nom`, `prenom`, `telephone`) values (?, ?, ?)) (Bindings: array (
  0 => 'BONHOURE',
  1 => 'Pierre',
  2 => '0657654599',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pa...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pa...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pa...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1428): Illuminate\Database\Connection->insert('insert into `pa...', Array)
#4 D:\xampp\htdocs\azertea\app\models\Populate.php(12): Illuminate\Database\Query\Builder->insert(Array)
#5 D:\xampp\htdocs\azertea\app\routes.php(16): Populate::go()
#6 [internal function]: {closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:25:11] log.ERROR: 500 - syntax error, unexpected '->' (T_OBJECT_OPERATOR) @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in D:\xampp\htdocs\azertea\app\models\Requete.php:40
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:25:39] log.ERROR: 500 - syntax error, unexpected '->' (T_OBJECT_OPERATOR) @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in D:\xampp\htdocs\azertea\app\models\Requete.php:67
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:26:21] log.ERROR: 500 - syntax error, unexpected '->' (T_OBJECT_OPERATOR) @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in D:\xampp\htdocs\azertea\app\models\Requete.php:90
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:26:36] log.ERROR: 500 - syntax error, unexpected '}' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in D:\xampp\htdocs\azertea\app\models\Requete.php:260
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:26:56] log.ERROR: 500 - syntax error, unexpected '^' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '^'' in D:\xampp\htdocs\azertea\app\models\Requete.php:300
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:32:53] log.ERROR: 500 - Array to string conversion @ /search
exception 'ErrorException' with message 'Array to string conversion' in D:\xampp\htdocs\azertea\app\models\Requete.php:214
Stack trace:
#0 D:\xampp\htdocs\azertea\app\models\Requete.php(214): Illuminate\Exception\Handler->handleError(8, 'Array to string...', 'D:\xampp\htdocs...', 214, Array)
#1 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(13): Requete->getMotCle(Array)
#2 [internal function]: SearchController->postSearch()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:33:28] log.ERROR: 500 - Array to string conversion @ /search
exception 'ErrorException' with message 'Array to string conversion' in D:\xampp\htdocs\azertea\app\models\Requete.php:214
Stack trace:
#0 D:\xampp\htdocs\azertea\app\models\Requete.php(214): Illuminate\Exception\Handler->handleError(8, 'Array to string...', 'D:\xampp\htdocs...', 214, Array)
#1 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(13): Requete->getMotCle(Array)
#2 [internal function]: SearchController->postSearch()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 04:38:08] log.ERROR: 500 - Object of class stdClass could not be converted to string (SQL: select `id_categorie`, `id_MC`, `poids` from `MC_cat` where `id_MC` = ?) (Bindings: array (
  0 => 
  stdClass::__set_state(array(
     'id' => 1,
  )),
)) @ /search
exception 'ErrorException' with message 'Object of class stdClass could not be converted to string' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(4096, 'Object of class...', 'D:\xampp\htdocs...', 58, Array)
#1 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(274): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `id_cate...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select `id_cate...', Array, Object(Closure))
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select `id_cate...', Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#8 D:\xampp\htdocs\azertea\app\models\Requete.php(167): Illuminate\Database\Query\Builder->get()
#9 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(16): Requete->getCategorieMotCle(Array)
#10 [internal function]: SearchController->postSearch()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#21 {main}

Next exception 'Exception' with message 'Object of class stdClass could not be converted to string (SQL: select `id_categorie`, `id_MC`, `poids` from `MC_cat` where `id_MC` = ?) (Bindings: array (
  0 => 
  stdClass::__set_state(array(
     'id' => 1,
  )),
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(ErrorException), 'select `id_cate...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select `id_cate...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select `id_cate...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\app\models\Requete.php(167): Illuminate\Database\Query\Builder->get()
#6 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(16): Requete->getCategorieMotCle(Array)
#7 [internal function]: SearchController->postSearch()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-12-06 04:39:21] log.ERROR: 500 - syntax error, unexpected 'foreach' (T_FOREACH) @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'foreach' (T_FOREACH)' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:16
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:39:37] log.ERROR: 500 - Object of class stdClass could not be converted to string (SQL: select `id_categorie`, `id_MC`, `poids` from `MC_cat` where `id_MC` = ?) (Bindings: array (
  0 => 
  stdClass::__set_state(array(
     'id' => 1,
  )),
)) @ /search
exception 'ErrorException' with message 'Object of class stdClass could not be converted to string' in D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php:58
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(4096, 'Object of class...', 'D:\xampp\htdocs...', 58, Array)
#1 D:\xampp\htdocs\azertea\vendor\maximebf\debugbar\src\DebugBar\DataCollector\PDO\TraceablePDOStatement.php(58): PDOStatement->execute(Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(274): DebugBar\DataCollector\PDO\TraceablePDOStatement->execute(Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `id_cate...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select `id_cate...', Array, Object(Closure))
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select `id_cate...', Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#8 D:\xampp\htdocs\azertea\app\models\Requete.php(167): Illuminate\Database\Query\Builder->get()
#9 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(17): Requete->getCategorieMotCle(Array)
#10 [internal function]: SearchController->postSearch()
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#21 {main}

Next exception 'Exception' with message 'Object of class stdClass could not be converted to string (SQL: select `id_categorie`, `id_MC`, `poids` from `MC_cat` where `id_MC` = ?) (Bindings: array (
  0 => 
  stdClass::__set_state(array(
     'id' => 1,
  )),
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(ErrorException), 'select `id_cate...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select `id_cate...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select `id_cate...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\app\models\Requete.php(167): Illuminate\Database\Query\Builder->get()
#6 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(17): Requete->getCategorieMotCle(Array)
#7 [internal function]: SearchController->postSearch()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-12-06 04:48:06] log.ERROR: 500 - syntax error, unexpected '}' @ /search
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in D:\xampp\htdocs\azertea\app\controllers\SearchController.php:17
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 04:48:17] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::in() @ /search
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::in()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 D:\xampp\htdocs\azertea\app\models\Requete.php(166): Illuminate\Database\Query\Builder->__call('in', Array)
#1 D:\xampp\htdocs\azertea\app\models\Requete.php(166): Illuminate\Database\Query\Builder->in('id_MC', Array)
#2 D:\xampp\htdocs\azertea\app\controllers\SearchController.php(18): Requete->getCategorieMotCle(Array)
#3 [internal function]: SearchController->postSearch()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSearch', Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSearch', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
